language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"

install:
  - "pip install coveralls"

script:
  - coverage run --source=. setup.py test

after_success:
  coveralls

notifications:
  email: false